### ISSUE TITLE
Resolve 'Undefined property: stdClass::$title_link'

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pul_base_deprecated#19]
After configuring the theme, I get the following notice at the top of my pages and can't seem to make it go away:

`Notice: Undefined property: stdClass::$title_link in include() (line 51 of /Users/shaune/Development/friends/sites/all/themes/pul_base/templates/block/block--nav.tpl.php).`

**Comment by kevinreiss** [comment]
Try enabling https://www.drupal.org/project/block_titlelink. We should add this a dependency to the base themes .info file.

**Comment by sdellis** [comment]
Actually, that was already enabled.  Perhaps there's another dependency that is not present?

**Comment by kevinreiss** [comment]
No, even if the module disabled it appears that code calling that variable expects that you will have set a value for the title to be hyperlinked. For now the part of https://github.com/pulibrary/pul_base/blob/d1680823fb3b9af3de08dd31310cff9f7d46e3d4/templates/block/block--nav.tpl.php#L51 that creates an <a> tag should probably be wrapped in an isset check for that value.
